export enum ConfigKey {
  FILE_DIRECTORY = 'FILE_DIRECTORY',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_DB = 'DATABASE_DB',

  NOTION_KEY = 'NOTION_KEY',
  NOTION_PROJECT_KEY = 'NOTION_PROJECT_KEY',
  NOTION_SKILL_KEY = 'NOTION_SKILL_KEY',
}
